---
title: alfacent-staging
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  projects:
    title: Projects
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    preview_image:
    permalink: "/projects/:title/"
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty

sass:
  style: compressed
  sass_dir: _sass

exclude: ['Gemfile', 'Gemfile.lock']
