---
title: alfacent-staging
timezone: UTC
url: "http://alfacent-staging.siteleaf.net/"
disqus_shortname: "alfacent-staging"
paginate: 5
paginate_path: "/blog/:num/"
contact_email: test@example.com
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  projects:
    title: Projects
    output: true
  aboutus:
    title: Information
    output: false
  blog_tags:
    title: Tags
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
    preview_image:
    permalink: "/projects/:title/"
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    tags:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: blog_tags
  values:
    layout: tag
    permalink: "/blog/tags/:title/"
permalink: pretty

sass:
  style: compressed
  sass_dir: _sass

gems:
  - 'jekyll-paginate'

exclude: ['Gemfile', 'Gemfile.lock']
